repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      - id: ruff
        args:
          - --config
          - .code_quality/ruff.toml

  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3
      args:
          - --config
          - .code_quality/pyproject_black.toml
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args:
          - -c
          - .code_quality/bandit.yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        args:
          - --config-file=.code_quality/mypy.ini
