#same as black
line-length = 100
target-version = "py39"
select = ["E", "F", "W", "PL", "I"]
ignore = ["E203"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "old",
    "env",
    ".env",
    ".venv",
    "migrations",
]
